version: '3'
services:
  web:
    build: .
    container_name: 'twilio-taskrouter-contact-center'
    ports:
     - '1080:3000'
    environment:
     - NODE_ENV=development
    volumes:
     - ./:/usr/src/app
     - /usr/src/app/node_modules
