require('dotenv').load();

module.exports = {
    TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
    TWILIO_API_KEY: process.env.TWILIO_API_KEY,
    TWILIO_API_SECRET: process.env.TWILIO_API_SECRET,
    TWILIO_TWIML_APP_SID: process.env.TWILIO_TWIML_APP_SID,
    TWILIO_CHAT_SERVICE_SID: process.env.TWILIO_CHAT_SERVICE_SID,
    TWILIO_NOTIFICATION_SERVICE_SID: process.env.TWILIO_NOTIFICATION_SERVICE_SID,
    TWILIO_TASKROUTER_WORKSPACE_SID: process.env.TWILIO_TASKROUTER_WORKSPACE_SID,
    TWILIO_SYNC_SERVICE_SID: process.env.TWILIO_SYNC_SERVICE_SID || 'default',
    TWILIO_CONFERENCE_NUMBER: process.env.TWILIO_CONFERENCE_NUMBER,
    TWILIO_TASKROUTER_WORKFLOW_SID: process.env.TWILIO_TASKROUTER_WORKFLOW_SID,
    NGROK_GLOBAL_DOMAIN: process.env.NGROK_GLOBAL_DOMAIN
}
